#!/bin/bash

pairs=( "BTC_ETH" "BTC_LTC" "BTC_XRP" "BTC_XMR" "BTC_DASH" "BTC_DCR" "BTC_BELA" "BTC_ETC" "BTC_ZEC" "BTC_STRAT" "BTC_FCT" "BTC_STR" "BTC_RBY" "BTC_DGB" "BTC_XEM" "BTC_DOGE" "BTC_GNT" "BTC_MAID" "BTC_LSK" "BTC_RIC" "BTC_CLAM" "BTC_STEEM" "BTC_SC" "BTC_REP" "BTC_NXC" "BTC_VOX" "BTC_POT" "BTC_AMP" "BTC_BTS" "BTC_EMC2" "BTC_SDC" "BTC_LBC" "BTC_NXT" "BTC_GAME" "BTC_XBC" "BTC_VIA" "BTC_PASC" "BTC_NAUT" "BTC_ARDR" "BTC_FLO" "BTC_HUC" "BTC_C2" "BTC_SYS" "BTC_RADS" "BTC_NSR" "BTC_NAV" "BTC_BCY" "BTC_QORA" "BTC_BLK" "BTC_GRC" "BTC_EXP" "BTC_XCP" "BTC_PPC" "BTC_BTM" "BTC_VTC" "BTC_IOC" "BTC_BCN" "BTC_XPM" "BTC_CURE" "BTC_SJCX" "BTC_BURST" "BTC_FLDC" "BTC_BTCD" "BTC_VRC" "BTC_QTL" "BTC_SBD" "BTC_MYR" "BTC_NMC" "BTC_NEOS" "BTC_QBK" "BTC_BBR" "BTC_PINK" "BTC_NOTE" "BTC_HZ" "BTC_XMG" "BTC_OMNI" "BTC_NOBL" "BTC_BITS" "BTC_XVC" "BTC_UNITY" "ETH_GNT" "ETH_ZEC" "ETH_ETC" "ETH_STEEM" "ETH_LSK" "ETH_REP" "XMR_LTC" "XMR_DASH" "XMR_ZEC" "XMR_MAID" "XMR_BCN" "XMR_NXT" "XMR_BBR" "XMR_BTCD" "XMR_BLK" "XMR_QORA" "USDT_BTC" "USDT_ETH" "USDT_LTC" "USDT_XRP" "USDT_XMR" "USDT_ETC" "USDT_DASH" "USDT_ZEC" "USDT_STR" "USDT_REP" "USDT_NXT" )

go install github.com/crypto-bank/go-orderbook/tools/orderbook_sync

for pair in "${pairs[@]}"
do
    orderbook_sync --db-path ~/orderbook --currency-pair ${pair}
    sleep 80
done
